# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: WindowsPool

steps:

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      
      Write-Host "Hello World from Powershell"

- task: TerraformInstaller@0
  inputs:
    terraformVersion: 'latest'

- task: TerraformTaskV2@2
  inputs:
    provider: 'aws'
    command: 'init'
    backendServiceAWS: 'AWSforTerraform'
    backendAWSBucketName: 'avdlpbucket'
    backendAWSKey: 'state/terraform.tfstate'

- task: TerraformTaskV2@2
  inputs:
    provider: 'aws'
    command: 'plan'
    environmentServiceNameAWS: 'AWSforTerraform'
- task: TerraformTaskV2@2
  inputs:
    provider: 'aws'
    command: 'apply'
    environmentServiceNameAWS: 'AWSforTerraform'
